#!/usr/bin/env node
// Links unpublished Foldworks packages into this workspace for local
// development of @formalang/workbench.
//
//   FOLDWORKS_DIR=../foldworks node scripts/foldworks-link.mjs
//   pnpm install
//
// FOLDWORKS_DIR is a Foldworks checkout whose packages are built
// (`pnpm build:packages`). Each package is packed into `.foldworks/` with
// `pnpm pack`, which resolves its `workspace:` and `catalog:` ranges, and a
// generated `.pnpmfile.cjs` points every `@foldworks/*` dependency at those
// tarballs. Both are gitignored. The install rewrites `pnpm-lock.yaml` with
// local paths: never commit it while linked. `--unlink` removes the hook and
// restores the lockfile.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packsDir = join(root, ".foldworks");
const hookPath = join(root, ".pnpmfile.cjs");

// The Foldworks packages the workbench uses, with their own Foldworks dependencies.
const PACKAGES = [
  "agent",
  "code-editor",
  "history",
  "keyboard",
  "outliner",
  "text-intelligence",
  "ui",
];

if (process.argv.includes("--unlink")) {
  rmSync(hookPath, { force: true });
  rmSync(packsDir, { recursive: true, force: true });
  execFileSync("git", ["checkout", "--", "pnpm-lock.yaml"], { cwd: root, stdio: "inherit" });
  console.log("Unlinked Foldworks. Run `pnpm install` to restore published packages.");
  process.exit(0);
}

const foldworks = process.env.FOLDWORKS_DIR;
if (!foldworks) {
  console.error("Set FOLDWORKS_DIR to a Foldworks checkout built with `pnpm build:packages`.");
  process.exit(1);
}
const foldworksDir = resolve(foldworks);

rmSync(packsDir, { recursive: true, force: true });
mkdirSync(packsDir, { recursive: true });

const tarballs = {};
for (const name of PACKAGES) {
  const dir = join(foldworksDir, "packages", name);
  if (!existsSync(join(dir, "dist"))) {
    console.error(`${dir} has no dist/. Run \`pnpm build:packages\` in ${foldworksDir}.`);
    process.exit(1);
  }
  const before = new Set(readdirSync(packsDir));
  execFileSync("pnpm", ["pack", "--pack-destination", packsDir], { cwd: dir, stdio: "ignore" });
  const packed = readdirSync(packsDir).find((file) => !before.has(file));
  const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  tarballs[manifest.name] = join(packsDir, packed);
}

const revision = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: foldworksDir })
  .toString()
  .trim();

writeFileSync(
  hookPath,
  `// Generated by scripts/foldworks-link.mjs from Foldworks ${revision}. Gitignored.
const tarballs = ${JSON.stringify(tarballs, null, 2)};

function link(dependencies) {
  for (const name of Object.keys(dependencies ?? {})) {
    if (tarballs[name]) dependencies[name] = "file:" + tarballs[name];
  }
}

module.exports = {
  hooks: {
    readPackage(manifest) {
      link(manifest.dependencies);
      link(manifest.devDependencies);
      link(manifest.optionalDependencies);
      return manifest;
    },
  },
};
`,
);

console.log(`Packed ${PACKAGES.length} Foldworks packages from ${foldworksDir} (${revision}).`);
console.log("Run `pnpm install`. Do not commit pnpm-lock.yaml while linked.");
